= Cashew Documentation
:toc:
:source-highlighter: pygments

{% macro src(section, language="python") %}
[source,{{ language }}]
----
{{ d['/cashew/plugin.py|pydoc'][section] }}
----
{% endmacro %}

{% macro test(section, language="python") %}
[source,{{ language }}]
----
{{ d['/tests/test_cashew.py|pydoc'][section] }}
----
{% endmacro %}

{% macro test2(section, language="python") %}
[source,{{ language }}]
----
{{ d['/tests/test_settings_from_other_classes.py|pydoc'][section] }}
----
{% endmacro %}

== Introduction

Cashew is a plugin system for python, based on the ideas in
<http://effbot.org/zone/metaclass-plugins.htm>.

The goal of Cashew is to let you easily modify the behavior of a tool by using
configuration options, and, when you need to, by writing custom code also.

This means that you can configure a system using a data format such as YAML or
JSON, or create a nice front-end for users which exposes the available
configuration options in a user-friendly way.

You identify a subclass and/or a preconfigured bundle of settings by an alias,
and settings can further be modified at runtime to allow for multiple levels of
configuration.

== Basic Usage

=== Creating a Base Class

The first step in creating a plugin system is to create a base class, which should be a subclass of the Plugin class, and which should specify PluginMeta as its metaclass:

{{ d['classes.py|idio|asciisyn']['imports'] }}
{{ d['classes.py|idio|asciisyn']['create-plugin-base-class'] }}

There's a little about the `__metaclass__` property 
http://docs.python.org/2/reference/datamodel.html#customizing-class-creation[here in the python docs]
and several articles online if you search.

You can do anything else you normally do with a base class, like implement
instance and class methods to be shared among all subclasses.

{{ d['classes.py|idio|asciisyn']['methods'] }}

You can make as many different base classes as you want in your project, and
each will be an independent plugin system. For example, in
http://dexy.it[dexy] the https://github.com/dexy/dexy/blob/develop/dexy/filter.py[Filter class], https://github.com/dexy/dexy/blob/develop/dexy/reporter.py[Reporter class], https://github.com/dexy/dexy/blob/develop/dexy/data.py[Data class] and
several others are implemented via plugins.

=== Plugin Registration

The `__init__` method in PluginMeta handles plugin registration:

{{ src('PluginMeta.__init__:source') }}

When this method is called on the base class itself (in our example the Data
class), it creates an empty dictionary named `plugins`, and when it is
subsequently called on subclasses, it calls the `register_plugin` method which
populates the `plugins` dictionary on the base class.

The `plugins` dictionary keys are the `aliases` which are defined for each
class we want to be accessible, and the values are a tuple of class names (or
instances) and dictionaries with settings. The key to Cashew's flexibility is
that the plugins dictionary can be populated directly, as well as being
populated automagically when the base class is subclassed.

In order for the automagic to happen, you need to actually load the python
modules in which subclasses are defined.

{{ d['usage1.py|idio|pycon|asciisyn']['plugins'] }}

A nice way to do this is with a
https://github.com/dexy/dexy/blob/develop/dexy/load_plugins.py[`load_plugins`]
module which does nothing but import all the modules in which you have defined
plugin subclasses.

To actually use plugins, `PluginMeta` defines a `create_instance` factory
method which takes an alias as its argument, and optionally accepts positional
and keyword arguments to be passed to a constructor.

[source,python]
----
{{ d['/cashew/plugin.py|pydoc']['PluginMeta.create_instance:source'] }}
----

Here's an example of using the `create_instance` method for a plugin based on
the `Data` class. As we saw above, the constructor `__init__` takes a single
positional argument, and we pass a positional argument to the `create_instance`
method:

{{ d['usage1.py|idio|pycon|asciisyn']['json-example-type'] }}

=== Basic Subclassing Example

Here are two examples of simple classes which subclass `Data`, and each define
a different style of presenting the contents of the `data` attribute:

{{ d['classes1.py|idio|asciisyn']['json-subclass'] }}

{{ d['classes1.py|idio|asciisyn']['csv-subclass'] }}

Required features:

- Subclass the `Data` class (directly or indirectly).
- Define one or more aliases (unless you don't want people to be able to use that class directly).
- Provide a docstring (or a 'help' setting).

Here's the full usage example, parts of which we have seen already.

We import the `Data` class from `classes.py`:

{{ d['usage1.py|idio|pycon|asciisyn']['import'] }}

We define some `example_data`:

{{ d['usage1.py|idio|pycon|asciisyn']['example-data'] }}

We create an instance of the `json` plugin, and call its `present` method:

{{ d['usage1.py|idio|pycon|asciisyn']['json-example'] }}

And we create an instance of the `csv` plugin and also call its `present` method:

{{ d['usage1.py|idio|pycon|asciisyn']['csv-example'] }}

=== Settings

To have user-settable settings, define a dictionary named `_settings` in your subclass:

{{ d['classes2.py|idio|asciisyn']['csv-settings'] }}

The keys of this dictionary should be hyphen- or underscore-separated setting
names, which will be accessible in hyphen format later, and the values should
usually be a tuple of (docstring, default value) but may be just a default
value if the docstring has already been defined in a parent class.

This dictionary will be combined with any other `_settings` dictionaries found
in any parent class all the way up to the `Data` base class.

Individual values can be retrieved by calling the `setting` method and passing
the setting name, and all values can be retrieved by calling the
`setting_values` method.

{{ d['usage2.py|idio|pycon|asciisyn']['csv-example'] }}

Then in your code, the settings should be used to control any behavior that can
be user-customizable. In this case many of the settings are passed directly to
the `csv` library, while the `write-header` setting is used to determine if the
`writeheader()` method will be called.

{{ d['classes2.py|idio|asciisyn']['csv-present'] }}

=== Settings for Other Classes

You may want to define a plugin which defines a new setting on a different plugin class.

For example in dexy, the website reporter defines some extra parameters on the
Document class so that you can specify for each document which website template
you'd like to use.

Here is a Report base class which defines an additional setting named `bar` on a class with alias `document`:

{{ test2("Report:source") }}

And also a Filter base class which defines a `foo` setting:

{{ test2("Filter:source") }}

On the Document class, which has alias `document`, there are no settings defined:

{{ test2("Document:source") }}

We create a plugin SomeKindOfDocument which is a Document:

{{ test2("SomeKindOfDocument:source") }}

And, we see that the `foo` and `bar` settings are available, even though these were not defined in Document or SomeKindOfDocument:

{{ test2("test_other_class_settings:source") }}

== Implementation Details

=== Plugin Registration

Let's review the `__init__` method and follow the methods it calls.

{{ src('PluginMeta.__init__:source') }}

The first line asserts that our plugin class inherits from `Plugin`. If this
were not the case then lots of expected behavior wouldn't work.

{{ test('test_must_inherit_from_plugin_class:source') }}

In the next two lines, if we detect `__metaclass__` in the class attributes
then we are creating a plugin base class, and so we want to initialize a
plugins dictionary. If not, then we have already created a base class and we
are creating a plugin subclass. In this case, if there are aliases specified,
we call the `register_plugin` method.

{{ src('PluginMeta.register_plugin:source') }}

The register plugin method may receive a list of aliases or a single alias, and it may receive a class name or an actual class. The first thing it does is standardize each of these.

{{ src('PluginMeta.standardize_alias_or_aliases:source') }}
{{ src('PluginMeta.get_reference_to_class:source') }}

The `get_reference_to_class` method will load a fully qualified class name automatically:

{{ test('test_get_reference_to_qualified_class:source') }}

If you want to be able to specify an unqualified class name then you need to
establish a mapping between class names and class objects in a
`load_class_from_locals` method, here's one way to do this:

{{ test('Data.load_class_from_locals:source') }}

And this allows you to do:

{{ test('test_get_reference_to_class:source') }}

You'll need to implement this one, by default it's disabled:

{{ src('PluginMeta.load_class_from_locals:source') }}

Here's the `register_plugin` source again since it's been a while since we've
seen it:

{{ src('PluginMeta.register_plugin:source') }}

The next block of text adds `aliases` and `help` settings so we can count on
these always being available. You need to provide a docstring which will be
used for the 'help' setting.

{{ src('PluginMeta.check_docstring:source') }}

Once the settings are normalized, then we are ready to actually add class
information to the plugins dictionary using the aliases as keys.

There's an option to add namespacing to plugins by implementing a different
`apply_prefix` class method in your plugin base class:

{{ src('PluginMeta.apply_prefix:source') }}

Up to this point we have been looking at registering plugins automatically when
their class is loaded, but because a plugin can be registered as an alias
linked to a class name and settings dictionary, we can capture this information
in a textual format.

The `register_plugins` method registers multiple plugins based on a dictionary:

{{ src('PluginMeta.register_plugins:source') }}

The dictionaries keys should be aliases, separated by the pipe symbol if
there's more than one of them. The values should be a tuple of
class-or-class-name and a settings dictionary. (You can redefine
`register_plugins` or create your own method which calls `register_plugin` and
come up with any other format you want.)

Here's an example:

{{ test('test_register_plugins:source') }}

The `register_plugins_from_dict` method makes it easy to define a simpler data
structure (one which will map easily to a YAML file), and it retrieves and
removes a `class` key and generates the required format for calling
`register_plugin`:

{{ src('PluginMeta.register_plugins_from_dict:source') }}

{{ test('test_register_plugins_from_dict:source') }}

And here's a convenience method which registers plugins specified in a YAML
file using `register_plugins_from_dict`:

{{ src('PluginMeta.register_plugins_from_yaml_file:source') }}

=== Creating Instances

The `create_instance` method uses the plugins dictionary we just populated to
create a new instance of the specified plugin class.

{{ src('PluginMeta.create_instance:source') }}

It uses the `get_reference_to_class` method we've already seen to retrive a
reference to the class, then creates a new instance. The `alias` attribute is
set on the new instance so we can later retrieve which alias was used to create
it.

If any positional or keyword arguments are passed to `create_instance` (after
the alias argument), these are assumed to be constructor arguments and are
passed to the constructor.

After the instance is created, we need to initialize the settings to the values
specified in various locations.

The `initialize_settings` method is called. This method is part of the
`Plugin` class, not `PluginMeta`, so it's an instance method of our newly
created object, not a class method.

{{ src('Plugin.initialize_settings:source') }}

The `_instance_settings` attribute is used to store active settings for a given
instance. The subsequent methods populate the dictionary using the
`update_settings` method, which does things like standardize the format from
underscore to hyphen, and checks to ensure settings include a help string if
this is the first time in the class hierarchy that they have been defined:

{{ src('Plugin.update_settings:source') }}
{{ src('Plugin._update_settings:source') }}

One issue is that when data is loaded from a file there is no way to
distinguish between a tuple and a list of length two, and a list of length two
may either be the desired value of a setting, or the first element may be a
helpstring and the second element may be the desired value. It is assumed that
if the setting does not already exist, then a list of length 2 should be
interpreted as a (helpstring, value,) tuple.

Returning to our `initialize_settings` method:

{{ src('Plugin.initialize_settings:source') }}

This is first populated by settings defined in parent classes, starting with
the earliest ancestor.

{{ src('Plugin.initialize_settings_from_parents:source') }}

{{ src('PluginMeta.imro:source') }}

You can provide an `_unset` list to remove settings you no longer wish to be
active:

{{ test('UnsetFoo:source') }}
{{ test('test_unsetting_settings:source') }}

Here's an example of a setting inheritance, here's a base class defining a
`foo` setting:

{{ test('TestSettingsBase:source') }}

Here's a subclass which doesn't alter the setting:

{{ test('NoSettingsOfMyOwn:source') }}
{{ test('test_no_settings_of_my_own:source') }}

Here's a subclass which does:

{{ test('OverrideFooSetting:source') }}
{{ test('test_override_settings:source') }}

Next, we initialize settings which may have been specified by other classes:

{{ src('Plugin.initialize_settings_from_other_classes:source') }}

And then we initialize settings using any kwargs that were passed to
`initialize_settings`:

{{ src('Plugin.initialize_settings_from_raw_kwargs:source') }}

Now returning to `create_instance`:

{{ src('PluginMeta.create_instance:source') }}

We see there is another call to `update_settings` and this is where settings
stored in the plugins dictionary are applied.

This is because `initialize_settings` may be called in the constructor and if
so it does not get called again here, so a separate call to `update_settings`
is required.

In addition to creating individual instances using `create_instance`, it is
possible to iterate over an instance of each type of plugin.

{{ src('PluginMeta.__iter__:source') }}

{{ test('test_iter:source') }}

=== Retrieving Settings

Individual setting values should be obtained by calling the `setting` method:

{{ src('Plugin.setting:source') }}

If you don't want a UserFeedback exception raised if the setting you ask for
doesn't exist, you can use the `safe_setting` method instead:

{{ src('Plugin.safe_setting:source') }}

{{ test('test_safe_setting:source') }}

The `setting_values` method returns a dictionary of all setting values:

{{ src('Plugin.setting_values:source') }}

If a setting starts with a dollar sign, it is assumed to be an environment variable, and the `setting` method will retreive the value of that environment variable.

{{ test('test_retrieve_environment_variables:source') }}

If there is no corresponding env var defined, a `UserFeedback` exception is raised:

{{ test('test_error_if_no_env_var:source') }}

If you actually need to start a value with a dollar sign, you can escape it:

{{ test('test_escaped_dollar_sign:source') }}

